/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Aluno;

/**
 *
 * @author alunocmc
 */
public class Interface2 extends javax.swing.JFrame {

    /**
     * Creates new form Interface2
     */
    
     public void exibir(Aluno a) {

        jLabelNome1.setText(a.getNome());
        jLabelSobrenome1.setText(a.getSobrenome());
        jLabelData1.setText(a.getNascimento());
        jLabelSexo1.setText(a.getSexo());
        jLabelRGM1.setText(a.getRGM());
        jLabelCurso1.setText(a.getCurso());

        System.out.println(a.getNome());
    }
    
    public Interface2() {
        setTitle("Meu Perfil de Aluno");
        
          

   

    initComponents();

}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelSobrenome = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelRGM = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelSobrenome1 = new javax.swing.JLabel();
        jLabelData1 = new javax.swing.JLabel();
        jLabelSexo1 = new javax.swing.JLabel();
        jLabelRGM1 = new javax.swing.JLabel();
        jLabelCurso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelSobrenome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSobrenome.setText("Sobrenome");

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelData.setText("Data Nascimento");

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSexo.setText("Sexo");

        jLabelRGM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRGM.setText("RGM");

        jLabelCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCurso.setText("Curso");

        jLabelNome1.setText("oi");

        jLabelSobrenome1.setText("oi");

        jLabelData1.setText("oi");

        jLabelSexo1.setText("oi");

        jLabelRGM1.setText("oi");

        jLabelCurso1.setText("oi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelData)
                    .addComponent(jLabelRGM)
                    .addComponent(jLabelNome1)
                    .addComponent(jLabelData1)
                    .addComponent(jLabelRGM1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSexo)
                    .addComponent(jLabelSobrenome)
                    .addComponent(jLabelCurso)
                    .addComponent(jLabelSobrenome1)
                    .addComponent(jLabelSexo1)
                    .addComponent(jLabelCurso1))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelSobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome1)
                    .addComponent(jLabelSobrenome1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData)
                    .addComponent(jLabelSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData1)
                    .addComponent(jLabelSexo1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRGM)
                    .addComponent(jLabelCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRGM1)
                    .addComponent(jLabelCurso1))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface2.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface2.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface2.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface2.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelCurso1;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelRGM;
    private javax.swing.JLabel jLabelRGM1;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSexo1;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelSobrenome1;
    // End of variables declaration//GEN-END:variables
}
